[project]
name = "aiot-nilm"
version = "0.1.0"
description = "AIoT Electricity Theft Detection using NILM and Isolation Forest"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyod>=3.5.2",
    "pandas>=2.2",
    "numpy>=2.0",
    "scipy>=1.13",
    "scikit-learn>=1.5",
    "pyarrow>=16.0",
    "streamlit>=1.36",
    "plotly>=5.22",
    "nilmtk",
    "xgboost>=3.2.0",
]

[tool.uv.sources]
nilmtk = { git = "https://github.com/nilmtk/nilmtk.git" }
